### ISSUE TITLE
API?

### ISSUE THREAD

**Issue by TheFiZi** [sebsauvage/ZeroBin#43]
Would it be possible to maintain security but offer a simple API for submitting content to a Zerobin deployment and get the secure URL back?

That'd make it really easy to make mobile phone apps and command line tools (Linux) for submitting content.

**Comment by marsjaninzmarsa** [comment]
You have couple [JavaScript CLI interpreters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Shells), you have [SJCL in Python](https://pypi.python.org/pypi/sjcl), you have other projects, so yes, it is possible (not such simple but can be done, even in multiple different ways) to do crypto on client side and still need ZeroBen for hosting of your paste.

I'll be glad if you can reopen this issue, because I'd wanna work on it in coordination witch sametmax/0bin#14 and authors of sametmax/0bin#39 and #48 (if they wanna to), and check compatibility of implementation in #57 with file upload option in 0bin.

I just think, that giving users ability to pasting whatever they like in whatever way they like to whatever ZeroBin-family service they like should be great and 100% compatible with idea of whole project, but it's not possible now (see sametmax/0bin#84).
And I wanna do it. :sunglasses:
