### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by sebie** [sebsauvage/ZeroBin#84]
The installation instructions, I think, are incorrect. 
After reading #80 I found out that you need a /tmp? 
Would anyone mind writing a guide as to how to install it? 

Thanks,

Sebie

**Comment by Popolon** [comment]
In fact, you need to create two directories with writing permission for web server :
* tmp
* data

**Comment by sebie** [comment]
Mind providing steps on how you did it @sebsauvage ?

It would be appreciated greatly.

**Comment by Popolon** [comment]
Well, in my sense, this piece of software has great security concerns, because the directories tmp and data where you give the web server write permission countains (autogenerated) php scripts.
* This means than you give permission to execute script on a directory where the webserver can write
* This means than if there is a whole somewhere in the server applications that can be exploited, the attacker can place a script in this directory and will be able to execute it localy by a remote call.

**Comment by axilleas** [comment]
I didn't encounter this issue those two dirs were created automatically. Perhaps if the dir doesn't have the right permissions, it gets skipped.

**Comment by sebie** [comment]
Might try it again, if it is working for y'all.

**Comment by drewbeer** [comment]
if you are using nginx, you should deny web access to /data/ and /tmp/ that way they are not browsable.

**Comment by creafrog** [comment]
Oh yeah tks 4 patch drewbeer ;)

**Comment by sebie** [comment]
Thanks for the help, I got it working for what I needed.
